export const INIT_INGREDIENTS = "INIT_INGREDIENTS"
export const SET_INCREDIENTS = "SET_INGREDIENTS"
export const UPDATE_INGREDIENTS = "UPDATE_INGREDIENTS"
export const FETCH_INGREDIENTS  = "FETECH_IGREDIENTS"
export const FETCH_INGREDIENTS_SUCCESS ="FETCH_INGREDIENTS_SUCCESS"
export const FETCH_INGREDIENT_FAILED = 'FETCH_INGREDIENTS_FAILED'

export const PURCHASE_BURGER = "PURCHASE_BURGER"
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS"
export const PURCHASE_BURGER_FAILED = "PURCHASE_BURGER_FAILED"